# Generated by Django 5.1.3 on 2024-12-01 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuarios', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.TextField(max_length=100)),
                ('senha', models.TextField(max_length=15)),
            ],
        ),
    ]
