# Generated by Django 5.1.3 on 2024-12-01 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id_usuarios',
            new_name='id_usuario',
        ),
    ]
